// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.17.3
// source: v1/auth_challenge.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AuthChallengeU2F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyHandle string `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	Challenge string `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	AppId     string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Version   string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AuthChallengeU2F) Reset() {
	*x = AuthChallengeU2F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_auth_challenge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthChallengeU2F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallengeU2F) ProtoMessage() {}

func (x *AuthChallengeU2F) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_challenge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallengeU2F.ProtoReflect.Descriptor instead.
func (*AuthChallengeU2F) Descriptor() ([]byte, []int) {
	return file_v1_auth_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *AuthChallengeU2F) GetKeyHandle() string {
	if x != nil {
		return x.KeyHandle
	}
	return ""
}

func (x *AuthChallengeU2F) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AuthChallengeU2F) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AuthChallengeU2F) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ChallengeU2F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChallengeU2F) Reset() {
	*x = ChallengeU2F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_auth_challenge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeU2F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeU2F) ProtoMessage() {}

func (x *ChallengeU2F) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_challenge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeU2F.ProtoReflect.Descriptor instead.
func (*ChallengeU2F) Descriptor() ([]byte, []int) {
	return file_v1_auth_challenge_proto_rawDescGZIP(), []int{1}
}

type ChallengeTOTP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChallengeTOTP) Reset() {
	*x = ChallengeTOTP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_auth_challenge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeTOTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeTOTP) ProtoMessage() {}

func (x *ChallengeTOTP) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_challenge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeTOTP.ProtoReflect.Descriptor instead.
func (*ChallengeTOTP) Descriptor() ([]byte, []int) {
	return file_v1_auth_challenge_proto_rawDescGZIP(), []int{2}
}

type SolvedChallengeU2F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SolvedChallengeU2F) Reset() {
	*x = SolvedChallengeU2F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_auth_challenge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolvedChallengeU2F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolvedChallengeU2F) ProtoMessage() {}

func (x *SolvedChallengeU2F) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_challenge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolvedChallengeU2F.ProtoReflect.Descriptor instead.
func (*SolvedChallengeU2F) Descriptor() ([]byte, []int) {
	return file_v1_auth_challenge_proto_rawDescGZIP(), []int{3}
}

type SolvedChallengeTOTP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SolvedChallengeTOTP) Reset() {
	*x = SolvedChallengeTOTP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_auth_challenge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolvedChallengeTOTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolvedChallengeTOTP) ProtoMessage() {}

func (x *SolvedChallengeTOTP) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_challenge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolvedChallengeTOTP.ProtoReflect.Descriptor instead.
func (*SolvedChallengeTOTP) Descriptor() ([]byte, []int) {
	return file_v1_auth_challenge_proto_rawDescGZIP(), []int{4}
}

var File_v1_auth_challenge_proto protoreflect.FileDescriptor

var file_v1_auth_challenge_proto_rawDesc = []byte{
	0x0a, 0x17, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x65, 0x6c, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x22,
	0x80, 0x01, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x55, 0x32, 0x46, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x55,
	0x32, 0x46, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x54,
	0x4f, 0x54, 0x50, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x55, 0x32, 0x46, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x6f, 0x6c,
	0x76, 0x65, 0x64, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x54, 0x4f, 0x54, 0x50,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x72, 0x61, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x6c,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x72, 0x6d, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_auth_challenge_proto_rawDescOnce sync.Once
	file_v1_auth_challenge_proto_rawDescData = file_v1_auth_challenge_proto_rawDesc
)

func file_v1_auth_challenge_proto_rawDescGZIP() []byte {
	file_v1_auth_challenge_proto_rawDescOnce.Do(func() {
		file_v1_auth_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_auth_challenge_proto_rawDescData)
	})
	return file_v1_auth_challenge_proto_rawDescData
}

var file_v1_auth_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_auth_challenge_proto_goTypes = []interface{}{
	(*AuthChallengeU2F)(nil),    // 0: teleport.terminal.v1.AuthChallengeU2F
	(*ChallengeU2F)(nil),        // 1: teleport.terminal.v1.ChallengeU2F
	(*ChallengeTOTP)(nil),       // 2: teleport.terminal.v1.ChallengeTOTP
	(*SolvedChallengeU2F)(nil),  // 3: teleport.terminal.v1.SolvedChallengeU2F
	(*SolvedChallengeTOTP)(nil), // 4: teleport.terminal.v1.SolvedChallengeTOTP
}
var file_v1_auth_challenge_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_auth_challenge_proto_init() }
func file_v1_auth_challenge_proto_init() {
	if File_v1_auth_challenge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_auth_challenge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthChallengeU2F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_auth_challenge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeU2F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_auth_challenge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeTOTP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_auth_challenge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolvedChallengeU2F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_auth_challenge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolvedChallengeTOTP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_auth_challenge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_auth_challenge_proto_goTypes,
		DependencyIndexes: file_v1_auth_challenge_proto_depIdxs,
		MessageInfos:      file_v1_auth_challenge_proto_msgTypes,
	}.Build()
	File_v1_auth_challenge_proto = out.File
	file_v1_auth_challenge_proto_rawDesc = nil
	file_v1_auth_challenge_proto_goTypes = nil
	file_v1_auth_challenge_proto_depIdxs = nil
}
