version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Deprecated APIs, requires manual changes.
      # TODO(xacrimon): Update Firestore and solve deprecations.
      - dependency-name: cloud.google.com/go/firestore
      # Breaks backwards compatibility
      - dependency-name: github.com/gravitational/ttlmap
      # TODO(greedy52): Update mongo-driver and fix API changes.
      - dependency-name: go.mongodb.org/mongo-driver
      # TODO(codingllama): Allow /x/crypto updates after upstream patch.
      - dependency-name: golang.org/x/crypto
      # Must be kept in-sync with libbpf
      - dependency-name: github.com/aquasecurity/libbpfgo
      # Forked/replaced dependencies
      - dependency-name: github.com/coreos/go-oidc
      - dependency-name: github.com/denisenkom/go-mssqldb
      - dependency-name: github.com/go-mysql-org/go-mysql
      - dependency-name: github.com/go-redis/redis/v9
      - dependency-name: github.com/gogo/protobuf
      - dependency-name: github.com/julienschmidt/httprouter
      - dependency-name: github.com/keys-pub/go-libfido2
      - dependency-name: github.com/pkg/sftp
      - dependency-name: github.com/sirupsen/logrus
      - dependency-name: github.com/vulcand/predicate
      # TODO(tross): Update after Firestore is updated
      - dependency-name: google.golang.org/genproto
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
    ignore:
      # TODO(codingllama): Allow /x/crypto updates after upstream patch.
      - dependency-name: golang.org/x/crypto
      # TODO(tross): Update after Firestore is updated
      - dependency-name: google.golang.org/genproto
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: cargo
    directory: "/lib/srv/desktop/rdp/rdpclient"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3
