/*
Copyright 2022 Gravitational, Inc.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package keys

import "context"

// getYubiKeyPrivateKey connects to a connected yubiKey and gets a private key
// matching the given touch requirement previously generated by a Teleport client.
// If no key exists, a trace.NotFound error will be returned. If the PIV slot is
// in use by a non-Teleport Client, a trace.CompareFailed error will be returned.
func GetYubiKeyPrivateKey(ctx context.Context, touchRequired bool) (*PrivateKey, error) {
	return getYubiKeyPrivateKey(ctx, touchRequired)
}

// generateYubiKeyPrivateKey connects to a connected yubiKey and generates a new
// private key matching the given touch requirement.
func GenerateYubiKeyPrivateKey(ctx context.Context, touchRequired bool) (*PrivateKey, error) {
	return generateYubiKeyPrivateKey(ctx, touchRequired)
}
